/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_OpenCV_GrayscaleMorphology */

#ifndef _Included_processor_OpenCV_GrayscaleMorphology
#define _Included_processor_OpenCV_GrayscaleMorphology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    edge
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_edge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
