/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_OpenCV_GrayscaleMorphology */

#ifndef _Included_processor_OpenCV_GrayscaleMorphology
#define _Included_processor_OpenCV_GrayscaleMorphology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    standardGradient
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_standardGradient
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    externalGradient
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_externalGradient
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    internalGradient
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_internalGradient
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    OBR
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_OBR
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_GrayscaleMorphology
 * Method:    CBR
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_GrayscaleMorphology_CBR
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
