/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_OpenCV_Filter */

#ifndef _Included_processor_OpenCV_Filter
#define _Included_processor_OpenCV_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_OpenCV_Filter
 * Method:    medianBlur
 * Signature: ([I[IIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_medianBlur
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     processor_OpenCV_Filter
 * Method:    meanBlur
 * Signature: ([I[IIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_meanBlur
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     processor_OpenCV_Filter
 * Method:    gaussianBlur
 * Signature: ([I[IIIID)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_gaussianBlur
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jdouble);

/*
 * Class:     processor_OpenCV_Filter
 * Method:    sobel
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_sobel
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_Filter
 * Method:    prewitt
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_prewitt
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_Filter
 * Method:    roberts
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Filter_roberts
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
