/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_OpenCV_BinaryMorphology */

#ifndef _Included_processor_OpenCV_BinaryMorphology
#define _Included_processor_OpenCV_BinaryMorphology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    distanceTransform
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_distanceTransform
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    skeleton
 * Signature: ([I[I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_skeleton
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    reconstruct
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_reconstruct
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    conditionalDilation
 * Signature: ([I[I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_conditionalDilation
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    standardEdge
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_standardEdge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    externalEdge
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_externalEdge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     processor_OpenCV_BinaryMorphology
 * Method:    internalEdge
 * Signature: ([I[IIIII)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_BinaryMorphology_internalEdge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
