/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_OpenCV_Morphology */

#ifndef _Included_processor_OpenCV_Morphology
#define _Included_processor_OpenCV_Morphology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_OpenCV_Morphology
 * Method:    erode
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Morphology_erode
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_Morphology
 * Method:    dilate
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Morphology_dilate
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_Morphology
 * Method:    open
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Morphology_open
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     processor_OpenCV_Morphology
 * Method:    close
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_processor_OpenCV_Morphology_close
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
